### ISSUE TITLE
panic: interface conversion: *xormadapter.Adapter is not persist.Adapter: missing method LoadPolicy

### ISSUE THREAD

**Issue by mrchar** [casbin/xorm-adapter#22]
```go
package main

import (
	"github.com/casbin/casbin/v2"
	_ "github.com/go-sql-driver/mysql"

	"github.com/casbin/xorm-adapter"
)

func main() {
	// Initialize a Xorm adapter and use it in a Casbin enforcer:
	// The adapter will use the MySQL database named "casbin".
	// If it doesn't exist, the adapter will create it automatically.
	a, _ := xormadapter.NewAdapter("mysql", "mysql_username:mysql_password@tcp(127.0.0.1:3306)/") // Your driver and data source. 

	// Or you can use an existing DB "abc" like this:
	// The adapter will use the table named "casbin_rule".
	// If it doesn't exist, the adapter will create it automatically.
	// a := xormadapter.NewAdapter("mysql", "mysql_username:mysql_password@tcp(127.0.0.1:3306)/abc", true)

	e, _ := casbin.NewEnforcer("examples/rbac_model.conf", a)
	
	// Load the policy from DB.
	e.LoadPolicy()
	
	// Check the permission.
	e.Enforce("alice", "data1", "read")
	
	// Modify the policy.
	// e.AddPolicy(...)
	// e.RemovePolicy(...)
	
	// Save the policy back to DB.
	e.SavePolicy()
}
```
```
panic: interface conversion: *xormadapter.Adapter is not persist.Adapter: missing method LoadPolicy

goroutine 1 [running]:
github.com/casbin/casbin/v2.NewEnforcer(0xc00012bf00, 0x2, 0x2, 0x1c, 0x0, 0x0)
        /home/char/go/pkg/mod/github.com/casbin/casbin/v2@v2.1.2/enforcer.go:84 +0x143
main.main()
        /home/char/Documents/nova/dingyue/authorization/test/adapter/xorm.go:23 +0xde
```

**Comment by mrchar** [comment]
go.mod
```
module authorization

go 1.13

require (
	github.com/casbin/casbin v1.9.1
	github.com/casbin/casbin/v2 v2.1.2
	github.com/casbin/xorm-adapter v1.0.0
	github.com/go-sql-driver/mysql v1.4.1
	github.com/go-xorm/xorm v0.7.9 // indirect
	google.golang.org/appengine v1.6.5 // indirect
)
```

**Comment by mrchar** [comment]
I guess it's because xorm-adapter v2's go.mod incorrectly declares the module as xorm-adapter.

**Comment by hsluoyz** [comment]
Can you make a PR to fix it?

**Comment by hsluoyz** [comment]
@nodece

**Comment by fengjihua** [comment]
do NOT work, fix please

`import "github.com/casbin/xorm-adapter/v2"`

> cannot load github.com/casbin/xorm-adapter/v2: cannot find module providing package github.com/casbin/xorm-adapter/v2

**Comment by hsluoyz** [comment]
@fengjihua can you make a fix PR?

**Comment by mrchar** [comment]
@hsluoyz can not fix with commit, maybe you should add a new tag like 2.0.1.

**Comment by hsluoyz** [comment]
Released: https://github.com/casbin/xorm-adapter/releases/tag/v2.0.1

**Comment by mrchar** [comment]
all works!

**Comment by fengjihua** [comment]
work like a charm! awesome!

**Comment by fengjihua** [comment]
> Released: https://github.com/casbin/xorm-adapter/releases/tag/v2.0.1

work like a charm! awesome!
